#BNF+IAT 1.0 UTF-8;
!grammar call;
!slot <oper>;
!slot <name>;
!start <acstart>;
<acstart>:[<oper>]<name>;
<oper>:点击|打开;
<name>:确定!id(100)|取消!id(101)|下一步!id(102)|上两步!id(103)|呼叫!id(104)|返回!id(105)|向右划!id(106)|放大!id(107)|缩小!id(108)|停止!id(109)|上移!id(110)|下移!id(111)|向左划!id(112)|开始!id(113)|设置!id(114)|挂断!id(115)|隐藏!id(116)|显示!id(117)|拍照!id(118)|切换!id(119);
